databases:
  - name: pg
    databaseName: railsdb_u9tr
    user: admin
    region: singapore

services:
  - type: web
    name: sample_rails
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample_rails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

